/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.bean.Cliente;
import Model.bean.Menu;
import Model.dao.ClienteDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Vitor França
 */
public class ClienteForm extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
    private final Menu controller;
    public ClienteForm() {
        initComponents();
        this.getBtnVoltarCliente().setVisible(false);
        this.getTxtCodigoCliente().setVisible(false);
        this.getLblCodigo().setVisible(false);
        this.controller = new Menu(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblErro = new javax.swing.JLabel();
        lblSucesso = new javax.swing.JLabel();
        btnVoltarCliente = new javax.swing.JButton();
        btnSalvarCliente = new javax.swing.JButton();
        lblTel = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblRg = new javax.swing.JLabel();
        txtRg = new javax.swing.JTextField();
        slctUf = new javax.swing.JComboBox<>();
        lblUf = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCodigoCliente = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        itemCliente = new javax.swing.JMenuItem();
        itemPagamento = new javax.swing.JMenuItem();
        itemDivida = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblErro.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblErro.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lblErro, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 320, 20));

        lblSucesso.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblSucesso.setForeground(new java.awt.Color(0, 153, 0));
        getContentPane().add(lblSucesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 300, 20));

        btnVoltarCliente.setBackground(new java.awt.Color(102, 102, 102));
        btnVoltarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltarCliente.setText("Voltar");
        btnVoltarCliente.setToolTipText("");
        btnVoltarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 600, 110, 40));

        btnSalvarCliente.setBackground(new java.awt.Color(0, 102, 204));
        btnSalvarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvarCliente.setText("Salvar");
        btnSalvarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 600, 130, 40));

        lblTel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTel.setForeground(new java.awt.Color(255, 255, 255));
        lblTel.setText("Telefone:");
        getContentPane().add(lblTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, -1, -1));

        txtTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelActionPerformed(evt);
            }
        });
        getContentPane().add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 530, 200, 30));

        lblEmail.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("E-mail:");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, -1, -1));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, 200, 30));

        lblRg.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblRg.setForeground(new java.awt.Color(255, 255, 255));
        lblRg.setText("CPF:");
        getContentPane().add(lblRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, -1, -1));

        txtRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRgActionPerformed(evt);
            }
        });
        getContentPane().add(txtRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 470, 200, 30));

        slctUf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO", "\t" }));
        slctUf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slctUfActionPerformed(evt);
            }
        });
        getContentPane().add(slctUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 90, 30));

        lblUf.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblUf.setForeground(new java.awt.Color(255, 255, 255));
        lblUf.setText("UF:");
        getContentPane().add(lblUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, -1, -1));

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Cadastrar Cliente");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, -1, -1));

        lblEndereco.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEndereco.setForeground(new java.awt.Color(255, 255, 255));
        lblEndereco.setText("Endereço:");
        getContentPane().add(lblEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, -1, -1));

        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, 200, 30));

        lblNome.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("Nome:");
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, -1, -1));

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 200, 30));

        txtCodigoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoClienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtCodigoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 200, 30));

        lblCodigo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(255, 255, 255));
        lblCodigo.setText("Código:");
        getContentPane().add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/form-PainelFundo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/61764.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenuCadastro.setText("Cadastro");

        itemCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/cliente-icone.png"))); // NOI18N
        itemCliente.setText("Cliente");
        itemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemClienteActionPerformed(evt);
            }
        });
        jMenuCadastro.add(itemCliente);

        itemPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/pagamento-icone.png"))); // NOI18N
        itemPagamento.setText("Pagamento");
        itemPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPagamentoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(itemPagamento);

        itemDivida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/money.png"))); // NOI18N
        itemDivida.setText("Dívida");
        itemDivida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDividaActionPerformed(evt);
            }
        });
        jMenuCadastro.add(itemDivida);

        jMenuBar1.add(jMenuCadastro);

        jMenu2.setText("Alteração");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtCodigoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoClienteActionPerformed

    private void slctUfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slctUfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_slctUfActionPerformed

    private void txtRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRgActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelActionPerformed

    private void btnVoltarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarClienteActionPerformed
        // TODO add your handling code here:
        Cliente cl = new Cliente();
        try {
            cl.voltar(this);
        } catch (Exception ex) {
            Logger.getLogger(ClienteForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVoltarClienteActionPerformed

    public JButton getBtnVoltarCliente() {
        return btnVoltarCliente;
    }

    public void setBtnVoltarCliente(JButton btnVoltarCliente) {
        this.btnVoltarCliente = btnVoltarCliente;
    }

    private void btnSalvarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarClienteActionPerformed
        // TODO add your handling code here:
        Cliente clienteBean = new Cliente();
        try {
            clienteBean.cadastrarCliente(this);
//        Cliente cliente = new Cliente();
//        ClienteDAO cl = new ClienteDAO();
//        cliente.setNomeCliente(txtNome.getText());
//        cliente.setDocumento(txtRg.getText());
//        cliente.setEndereco(txtEndereco.getText());
//        cliente.setTelefone(txtTel.getText());
//        cliente.setUf(slctUf.getSelectedItem().toString());


//        cl.save(cliente);
        } catch (SQLException ex) {
            Logger.getLogger(ClienteForm.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    
        
       
    }//GEN-LAST:event_btnSalvarClienteActionPerformed

    public JLabel getLblErro() {
        return lblErro;
    }

    public void setLblErro(JLabel lblErro) {
        this.lblErro = lblErro;
    }

    public JButton getBtnSalvarCliente() {
        return btnSalvarCliente;
    }

    public void setBtnSalvarCliente(JButton btnSalvarCliente) {
        this.btnSalvarCliente = btnSalvarCliente;
    }

    public JLabel getLblCodigo() {
        return lblCodigo;
    }

    public void setLblCodigo(JLabel lblCodigo) {
        this.lblCodigo = lblCodigo;
    }

    public JLabel getLblEmail() {
        return lblEmail;
    }

    public void setLblEmail(JLabel lblEmail) {
        this.lblEmail = lblEmail;
    }

    public JLabel getLblEndereco() {
        return lblEndereco;
    }

    public void setLblEndereco(JLabel lblEndereco) {
        this.lblEndereco = lblEndereco;
    }

    public JLabel getLblNome() {
        return lblNome;
    }

    public void setLblNome(JLabel lblNome) {
        this.lblNome = lblNome;
    }

    public JLabel getLblRg() {
        return lblRg;
    }

    public void setLblRg(JLabel lblRg) {
        this.lblRg = lblRg;
    }

    public JLabel getLblTel() {
        return lblTel;
    }

    public void setLblTel(JLabel lblTel) {
        this.lblTel = lblTel;
    }

    public JLabel getLblUf() {
        return lblUf;
    }

    public void setLblUf(JLabel lblUf) {
        this.lblUf = lblUf;
    }

    public JTextField getTxtCodigoCliente() {
        return txtCodigoCliente;
    }

    public void setTxtCodigoCliente(JTextField txtCodigoCliente) {
        this.txtCodigoCliente = txtCodigoCliente;
    }

    public JLabel getLblSucesso() {
        return lblSucesso;
    }

    public void setLblSucesso(JLabel lblSucesso) {
        this.lblSucesso = lblSucesso;
    }

    public JComboBox<String> getSlctUf() {
        return slctUf;
    }

    public void setSlctUf(JComboBox<String> slctUf) {
        this.slctUf = slctUf;
    }

    public JTextField getTxtEmail() {
        return txtEmail;
    }

    public void setTxtEmail(JTextField txtEmail) {
        this.txtEmail = txtEmail;
    }

    public JTextField getTxtEndereco() {
        return txtEndereco;
    }

    public JLabel getLblTitulo() {
        return lblTitulo;
    }

    public void setLblTitulo(JLabel lblTitulo) {
        this.lblTitulo = lblTitulo;
    }

    public void setTxtEndereco(JTextField txtEndereco) {
        this.txtEndereco = txtEndereco;
    }

    public JTextField getTxtNome() {
        return txtNome;
    }

    public void setTxtNome(JTextField txtNome) {
        this.txtNome = txtNome;
    }

    public JTextField getTxtRg() {
        return txtRg;
    }

    public void setTxtRg(JTextField txtRg) {
        this.txtRg = txtRg;
    }

    public JTextField getTxtTel() {
        return txtTel;
    }

    public void setTxtTel(JTextField txtTel) {
        this.txtTel = txtTel;
    }

    private void itemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemClienteActionPerformed
        // TODO add your handling code here:
        this.controller.navegar("cliente");
    }//GEN-LAST:event_itemClienteActionPerformed

    private void itemPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPagamentoActionPerformed
        // TODO add your handling code here:
        this.controller.navegar("pagamento");
    }//GEN-LAST:event_itemPagamentoActionPerformed

    private void itemDividaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDividaActionPerformed
        // TODO add your handling code here:
        this.controller.navegar("divida");
    }//GEN-LAST:event_itemDividaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarCliente;
    private javax.swing.JButton btnVoltarCliente;
    private javax.swing.JMenuItem itemCliente;
    private javax.swing.JMenuItem itemDivida;
    private javax.swing.JMenuItem itemPagamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblErro;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRg;
    private javax.swing.JLabel lblSucesso;
    private javax.swing.JLabel lblTel;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUf;
    private javax.swing.JComboBox<String> slctUf;
    private javax.swing.JTextField txtCodigoCliente;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRg;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
