/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Model.bean.Divida;
import Model.bean.Menu;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Vitor França
 */
public class DividaForm extends javax.swing.JFrame {
private final Menu controller;
private final DividaForm view= this;
    /** Creates new form Divida */
    public DividaForm() {
        initComponents();
        this.controller = new Menu(this);
        view.getLblCodigo().setVisible(false);
        view.getTxtCodigoDivida().setVisible(false);
//        view.getBtnVoltarDivida().setVisible(false);
    }

  

    public JTextField getTxtCodigoDivida() {
        return txtCodigoDivida;
    }

    public void setTxtCodigoDivida(JTextField txtCodigoDivida) {
        this.txtCodigoDivida = txtCodigoDivida;
    }

    public JTextField getTxtDivida() {
        return txtDivida;
    }

    public void setTxtDivida(JTextField txtDivida) {
        this.txtDivida = txtDivida;
    }

    public JComboBox<String> getSlcCredor() {
        return slcCredor;
    }

    public void setSlcCredor(JComboBox<String> slcCredor) {
        this.slcCredor = slcCredor;
    }

    public JComboBox<String> getSlcDevedor() {
        return slcDevedor;
    }

    public void setSlcDevedor(JComboBox<String> slcDevedor) {
        this.slcDevedor = slcDevedor;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDataAtualizacao = new javax.swing.JTextField();
        lblErro = new javax.swing.JLabel();
        lblSucesso = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        slcDevedor = new javax.swing.JComboBox<>();
        slcCredor = new javax.swing.JComboBox<>();
        btnVoltarDivida = new javax.swing.JButton();
        btnSalvarDivida = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblDevedor = new javax.swing.JLabel();
        lblDivida = new javax.swing.JLabel();
        txtDivida = new javax.swing.JTextField();
        txtCodigoDivida = new javax.swing.JTextField();
        lblCredor = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        itemCliente = new javax.swing.JMenuItem();
        MenuConsulta = new javax.swing.JMenu();
        consultaItemCliente = new javax.swing.JMenuItem();
        consultaItemDivida = new javax.swing.JMenuItem();
        consultaItemPagamento = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDataAtualizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataAtualizacaoActionPerformed(evt);
            }
        });
        getContentPane().add(txtDataAtualizacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 200, 30));

        lblErro.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblErro.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lblErro, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 320, 20));

        lblSucesso.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblSucesso.setForeground(new java.awt.Color(0, 153, 0));
        getContentPane().add(lblSucesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 300, 20));

        lblData.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblData.setForeground(new java.awt.Color(255, 255, 255));
        lblData.setText("Data de atualização:");
        getContentPane().add(lblData, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, -1, -1));

        getContentPane().add(slcDevedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, 180, 30));

        getContentPane().add(slcCredor, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, 180, 30));

        btnVoltarDivida.setBackground(new java.awt.Color(102, 102, 102));
        btnVoltarDivida.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltarDivida.setText("Voltar");
        btnVoltarDivida.setToolTipText("");
        btnVoltarDivida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarDividaActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltarDivida, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, 110, 40));

        btnSalvarDivida.setBackground(new java.awt.Color(0, 102, 204));
        btnSalvarDivida.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvarDivida.setText("Salvar");
        btnSalvarDivida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarDividaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvarDivida, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, 130, 40));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Visualizar Dívida");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, -1, -1));

        lblDevedor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDevedor.setForeground(new java.awt.Color(255, 255, 255));
        lblDevedor.setText("Devedor:");
        getContentPane().add(lblDevedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, -1, -1));

        lblDivida.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDivida.setForeground(new java.awt.Color(255, 255, 255));
        lblDivida.setText("Dívida:");
        getContentPane().add(lblDivida, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, -1, -1));

        txtDivida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDividaActionPerformed(evt);
            }
        });
        getContentPane().add(txtDivida, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 200, 30));

        txtCodigoDivida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoDividaActionPerformed(evt);
            }
        });
        getContentPane().add(txtCodigoDivida, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 200, 30));

        lblCredor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCredor.setForeground(new java.awt.Color(255, 255, 255));
        lblCredor.setText("Credor:");
        getContentPane().add(lblCredor, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, -1, -1));

        lblCodigo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(255, 255, 255));
        lblCodigo.setText("Código:");
        getContentPane().add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/form-PainelFundo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/61764.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenuCadastro.setText("Cadastro");

        itemCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/cliente-icone.png"))); // NOI18N
        itemCliente.setText("Cliente");
        itemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemClienteActionPerformed(evt);
            }
        });
        jMenuCadastro.add(itemCliente);

        jMenuBar1.add(jMenuCadastro);

        MenuConsulta.setText("Consulta");

        consultaItemCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/cliente-icone.png"))); // NOI18N
        consultaItemCliente.setText("Cliente");
        consultaItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaItemClienteActionPerformed(evt);
            }
        });
        MenuConsulta.add(consultaItemCliente);

        consultaItemDivida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/money.png"))); // NOI18N
        consultaItemDivida.setText("Dívida");
        consultaItemDivida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaItemDividaActionPerformed(evt);
            }
        });
        MenuConsulta.add(consultaItemDivida);

        consultaItemPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/pagamento-icone.png"))); // NOI18N
        consultaItemPagamento.setText("Pagamento");
        consultaItemPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaItemPagamentoActionPerformed(evt);
            }
        });
        MenuConsulta.add(consultaItemPagamento);

        jMenuBar1.add(MenuConsulta);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoDividaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoDividaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoDividaActionPerformed

    private void txtDividaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDividaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDividaActionPerformed

    public JButton getBtnSalvarDivida() {
        return btnSalvarDivida;
    }

    public void setBtnSalvarDivida(JButton btnSalvarDivida) {
        this.btnSalvarDivida = btnSalvarDivida;
    }

    public JButton getBtnVoltarDivida() {
        return btnVoltarDivida;
    }

    public void setBtnVoltarDivida(JButton btnVoltarDivida) {
        this.btnVoltarDivida = btnVoltarDivida;
    }

    public JLabel getLblErro() {
        return lblErro;
    }

    public void setLblErro(JLabel lblErro) {
        this.lblErro = lblErro;
    }

    public JLabel getLblSucesso() {
        return lblSucesso;
    }

    public void setLblSucesso(JLabel lblSucesso) {
        this.lblSucesso = lblSucesso;
    }

    private void btnSalvarDividaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarDividaActionPerformed
        // TODO add your handling code here:
        Divida divida = new Divida();
    try {
        divida.salvarDivida(this.view);
    } catch (ParseException ex) {
        Logger.getLogger(DividaForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnSalvarDividaActionPerformed

    public JLabel getLblCodigo() {
        return lblCodigo;
    }

    public void setLblCodigo(JLabel lblCodigo) {
        this.lblCodigo = lblCodigo;
    }

    public JLabel getLblCredor() {
        return lblCredor;
    }

    public void setLblCredor(JLabel lblCredor) {
        this.lblCredor = lblCredor;
    }

    public JLabel getLblData() {
        return lblData;
    }

    public void setLblData(JLabel lblData) {
        this.lblData = lblData;
    }

    public JLabel getLblDevedor() {
        return lblDevedor;
    }

    public void setLblDevedor(JLabel lblDevedor) {
        this.lblDevedor = lblDevedor;
    }

  

    public JLabel getLblDivida() {
        return lblDivida;
    }

    public void setLblDivida(JLabel lblDivida) {
        this.lblDivida = lblDivida;
    }

    private void btnVoltarDividaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarDividaActionPerformed
        // TODO add your handling code here:
        Divida dividaBean = new Divida();
    try {
        dividaBean.voltar(view);
    } catch (Exception ex) {
        Logger.getLogger(DividaForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnVoltarDividaActionPerformed

    public JTextField getTxtDataAtualizacao() {
        return txtDataAtualizacao;
    }

    public void setTxtDataAtualizacao(JTextField txtDataAtualizacao) {
        this.txtDataAtualizacao = txtDataAtualizacao;
    }

    private void itemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemClienteActionPerformed
        // TODO add your handling code here:
        this.controller.navegar("cliente");
    }//GEN-LAST:event_itemClienteActionPerformed

    private void consultaItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaItemClienteActionPerformed
        // TODO add your handling code here:
        this.controller.navegar("cliente_consulta");
    }//GEN-LAST:event_consultaItemClienteActionPerformed

    private void consultaItemDividaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaItemDividaActionPerformed
        // TODO add your handling code here:
        this.controller.navegar("divida_consulta");
    }//GEN-LAST:event_consultaItemDividaActionPerformed

    private void consultaItemPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaItemPagamentoActionPerformed
        // TODO add your handling code here:
        this.controller.navegar("pagamento_consulta");
    }//GEN-LAST:event_consultaItemPagamentoActionPerformed

    private void txtDataAtualizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataAtualizacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataAtualizacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DividaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DividaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DividaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DividaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DividaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuConsulta;
    private javax.swing.JButton btnSalvarDivida;
    private javax.swing.JButton btnVoltarDivida;
    private javax.swing.JMenuItem consultaItemCliente;
    private javax.swing.JMenuItem consultaItemDivida;
    private javax.swing.JMenuItem consultaItemPagamento;
    private javax.swing.JMenuItem itemCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCredor;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDevedor;
    private javax.swing.JLabel lblDivida;
    private javax.swing.JLabel lblErro;
    private javax.swing.JLabel lblSucesso;
    private javax.swing.JComboBox<String> slcCredor;
    private javax.swing.JComboBox<String> slcDevedor;
    private javax.swing.JTextField txtCodigoDivida;
    private javax.swing.JTextField txtDataAtualizacao;
    private javax.swing.JTextField txtDivida;
    // End of variables declaration//GEN-END:variables

}
