/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.bean.Menu;

/**
 *
 * @author Vitor França
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private final Menu controller;

    /**
     * Creates new form MenuPrincial
     */
    public MenuPrincipal() {
        initComponents();
        this.controller = new Menu(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        itemCliente = new javax.swing.JMenuItem();
        MenuConsulta = new javax.swing.JMenu();
        consultaItemCliente = new javax.swing.JMenuItem();
        consultaItemDivida = new javax.swing.JMenuItem();
        consultaItemPagamento = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/61764.jpg"))); // NOI18N

        jMenuCadastro.setText("Cadastro");

        itemCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/cliente-icone.png"))); // NOI18N
        itemCliente.setText("Cliente");
        itemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemClienteActionPerformed(evt);
            }
        });
        jMenuCadastro.add(itemCliente);

        jMenuBar1.add(jMenuCadastro);

        MenuConsulta.setText("Consulta");

        consultaItemCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/cliente-icone.png"))); // NOI18N
        consultaItemCliente.setText("Cliente");
        consultaItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaItemClienteActionPerformed(evt);
            }
        });
        MenuConsulta.add(consultaItemCliente);

        consultaItemDivida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/money.png"))); // NOI18N
        consultaItemDivida.setText("Dívida");
        consultaItemDivida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaItemDividaActionPerformed(evt);
            }
        });
        MenuConsulta.add(consultaItemDivida);

        consultaItemPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icones/pagamento-icone.png"))); // NOI18N
        consultaItemPagamento.setText("Pagamento");
        consultaItemPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaItemPagamentoActionPerformed(evt);
            }
        });
        MenuConsulta.add(consultaItemPagamento);

        jMenuBar1.add(MenuConsulta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultaItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaItemClienteActionPerformed
        // TODO add your handling code here:
        this.controller.navegar("cliente_consulta");
    }//GEN-LAST:event_consultaItemClienteActionPerformed

    private void consultaItemDividaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaItemDividaActionPerformed
        // TODO add your handling code here:
        this.controller.navegar("divida_consulta");
    }//GEN-LAST:event_consultaItemDividaActionPerformed

    private void consultaItemPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaItemPagamentoActionPerformed
        // TODO add your handling code here:
        this.controller.navegar("pagamento_consulta");
    }//GEN-LAST:event_consultaItemPagamentoActionPerformed

    private void itemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemClienteActionPerformed
        // TODO add your handling code here:
        this.controller.navegar("cliente");
    }//GEN-LAST:event_itemClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuConsulta;
    private javax.swing.JMenuItem consultaItemCliente;
    private javax.swing.JMenuItem consultaItemDivida;
    private javax.swing.JMenuItem consultaItemPagamento;
    private javax.swing.JMenuItem itemCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    // End of variables declaration//GEN-END:variables
}
